name: TaskSchedulerApp
options:
  deploymentTarget:
    iOS: "17.0"
targets:
  TaskSchedulerApp:
    type: application
    platform: iOS
    sources:
      - path: Sources
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akisliuk-cloud.taskscheduler
        INFOPLIST_FILE: Resources/Info.plist
        SWIFT_VERSION: 5.9
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
schemes:
  TaskSchedulerApp:
    build:
      targets:
        TaskSchedulerApp: all
    run:
      config: Debug
