workflows:
  ios_sim_to_appetize:
    name: iOS Simulator → Appetize
    max_build_duration: 60
    environment:
      groups:
        - appetize
      vars:
        # Vars are kept for clarity, but we’ll use explicit paths in scripts to avoid UI resets
        APP_NAME: "TaskSchedulerApp"
        SCHEME_NAME: "TaskSchedulerApp"
        WORKSPACE_OR_PROJECT: "ios-app/TaskSchedulerApp.xcodeproj"
      xcode: 16.1
      cocoapods: default

    scripts:
      - name: Show Xcode version
        script: xcodebuild -version

      - name: Install XcodeGen (resilient, no auto-update)
        script: |
          set -euo pipefail
          if command -v xcodegen >/dev/null 2>&1; then
            echo "XcodeGen already installed:"
            xcodegen --version || true
          else
            # Prevent brew from failing due to large/old installs
            export HOMEBREW_NO_AUTO_UPDATE=1
            export HOMEBREW_NO_INSTALL_CLEANUP=1
            brew install xcodegen || brew upgrade xcodegen || true
            xcodegen --version || true
          fi

          
      - name: Generate Xcode project with XcodeGen
        script: |
          set -euo pipefail
          # Normalize common misnaming
          [ -f ios-app/project.yaml ] && mv ios-app/project.yaml ios-app/project.yml || true

          echo "Before xcodegen, ios-app contains:"
          ls -la ios-app

          # Generate from inside ios-app (so output lands in ios-app/)
          pushd ios-app >/dev/null
          xcodegen generate --spec project.yml
          echo "After xcodegen, ios-app contains:"
          ls -la
          popd >/dev/null

      - name: Verify Swift sources exist
        script: |
          set -euo pipefail
          echo "Swift files under ios-app/Sources:"
          find ios-app/Sources -type f -name "*.swift" -print | sort
          
          # Required files for this project layout
          test -f ios-app/Sources/AppState.swift || (echo "❌ Missing ios-app/Sources/AppState.swift" && exit 1)
          test -f ios-app/Sources/ContentView.swift || (echo "❌ Missing ios-app/Sources/ContentView.swift" && exit 1)
          test -f ios-app/Sources/TaskSchedulerApp.swift || (echo "❌ Missing ios-app/Sources/TaskSchedulerApp.swift" && exit 1)
          # TaskModels.swift is optional if its contents were merged elsewhere; keep or drop this check as needed:
          # test -f ios-app/Sources/TaskModels.swift || (echo "❌ Missing ios-app/Sources/TaskModels.swift" && exit 1)
          
          echo "✅ Source verification passed."

      - name: Build .app for iOS Simulator (unsigned)
        script: |
          set -euo pipefail
          DERIVED="ios-app/build_dir"

          xcodebuild \
            -project "ios-app/TaskSchedulerApp.xcodeproj" \
            -scheme "TaskSchedulerApp" \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
            -derivedDataPath "$DERIVED" \
            -destination-timeout 120 \
            build | xcpretty

          APP_PATH="$(/usr/bin/find "$DERIVED/Build/Products/Debug-iphonesimulator" -maxdepth 1 -type d -name "TaskSchedulerApp.app" -print -quit)"
          if [ -z "$APP_PATH" ]; then
            echo "❌ Could not find TaskSchedulerApp.app in Debug-iphonesimulator."
            echo "Products dir:"; ls -la "$DERIVED/Build/Products" || true
            exit 1
          fi

          cd "$(dirname "$APP_PATH")"
          zip -qry "TaskSchedulerApp.zip" "TaskSchedulerApp.app"
          echo "ZIPPED_APP=$(pwd)/TaskSchedulerApp.zip" >> $CM_ENV

      - name: Show CFBundleIdentifier inside built .app
        script: |
          set -euo pipefail
          APP_NAME="${APP_NAME:-TaskSchedulerApp}"

          # Candidate locations for DerivedData products
          CANDIDATES=(
            "ios-app/build_dir/Build/Products/Debug-iphonesimulator"
            "build_dir/Build/Products/Debug-iphonesimulator"
          )

          APP_PATH=""
          for d in "${CANDIDATES[@]}"; do
            if [ -d "$d" ]; then
              found="$(/usr/bin/find "$d" -maxdepth 1 -type d -name "${APP_NAME}.app" -print -quit || true)"
              if [ -n "$found" ]; then
                APP_PATH="$found"
                break
              fi
            fi
          done

          if [ -z "$APP_PATH" ]; then
            echo "❌ Could not locate ${APP_NAME}.app in expected simulator output folders."
            echo "Contents of candidates (if present):"
            for d in "${CANDIDATES[@]}"; do
              echo "--- $d ---"
              ls -la "$d" || true
            done
            exit 1
          fi

          echo "✅ Found app at: $APP_PATH"
          /usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$APP_PATH/Info.plist" || {
            echo "⚠️ Could not read CFBundleIdentifier from Info.plist"; exit 1;
          }

      - name: Validate built .app for Appetize
        script: |
          set -euo pipefail
          APP_NAME="${APP_NAME:-TaskSchedulerApp}"

          # Locate the .app
          CANDIDATES=(
            "ios-app/build_dir/Build/Products/Debug-iphonesimulator"
            "build_dir/Build/Products/Debug-iphonesimulator"
          )
          APP_DIR=""
          for d in "${CANDIDATES[@]}"; do
            if [ -d "$d/${APP_NAME}.app" ]; then APP_DIR="$d/${APP_NAME}.app"; break; fi
          done
          if [ -z "$APP_DIR" ]; then
            echo "❌ Could not find ${APP_NAME}.app in Debug-iphonesimulator"; exit 1
          fi
          echo "✅ .app found at: $APP_DIR"

          # 1) Info.plist must have critical keys
          echo "---- Info.plist keys ----"
          /usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$APP_DIR/Info.plist" || { echo "❌ CFBundleIdentifier missing"; exit 1; }
          /usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$APP_DIR/Info.plist" || { echo "❌ CFBundleShortVersionString missing"; exit 1; }
          /usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$APP_DIR/Info.plist" || { echo "❌ CFBundleVersion missing"; exit 1; }
          /usr/libexec/PlistBuddy -c 'Print :CFBundleExecutable' "$APP_DIR/Info.plist" || { echo "❌ CFBundleExecutable missing"; exit 1; }
          /usr/libexec/PlistBuddy -c 'Print :CFBundleSupportedPlatforms:0' "$APP_DIR/Info.plist" || { echo "❌ CFBundleSupportedPlatforms missing"; exit 1; }

          # 2) Binary must be arm64 simulator
          EXEC=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleExecutable' "$APP_DIR/Info.plist")
          BIN_PATH="$APP_DIR/$EXEC"
          if [ ! -f "$BIN_PATH" ]; then
            echo "❌ Executable not found at $BIN_PATH"; exit 1
          fi
          echo "---- Binary architectures ----"
          lipo -info "$BIN_PATH" || true
          if ! lipo -info "$BIN_PATH" | grep -q 'arm64'; then
            echo "❌ Binary is not arm64. Appetize requires arm64 simulator builds."
            echo "Hint: set ARCHS=arm64 for iphonesimulator or pass -arch arm64 to xcodebuild."
            exit 1
          fi

          # 3) Zip content preview
          echo "---- Zip preview ----"
          (cd "$(dirname "$APP_DIR")" && zip -qry "${APP_NAME}.zip" "${APP_NAME}.app" && echo "ZIPPED_APP=$(pwd)/${APP_NAME}.zip" >> $CM_ENV)
          unzip -l "$(dirname "$APP_DIR")/${APP_NAME}.zip" | head -n 20

          
      - name: Upload to Appetize (create new app)
        script: |
          set -euo pipefail
          if [ -z "${APPETIZE_API_KEY:-}" ]; then
            echo "❌ APPETIZE_API_KEY is not set"
            exit 1
          fi

          RESP=$(curl -sS -X POST "https://api.appetize.io/v1/apps" \
            -H "X-API-KEY: $APPETIZE_API_KEY" \
            -F "file=@${ZIPPED_APP}" \
            -F "platform=ios")

          echo "Appetize response: $RESP"

          PUBLIC_KEY=$(echo "$RESP" | jq -r '.publicKey // empty')
          if [ -z "$PUBLIC_KEY" ]; then
            echo "❌ Failed to get publicKey from Appetize response."
            exit 1
          fi

          # Let Appetize pick a compatible device/OS
          LAUNCH_URL="https://appetize.io/app/${PUBLIC_KEY}?scale=75"
          echo "LAUNCH_URL=${LAUNCH_URL}" >> $CM_ENV
          echo "✅ Open in browser: ${LAUNCH_URL}"

    artifacts:
      - ios-app/build_dir/Build/Products/Debug-iphonesimulator/*.app
      - ios-app/build_dir/Build/Products/Debug-iphonesimulator/*.zip
